[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-operator"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  ".","app", "ias/lambda"
]